name: NPM Publish
on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  npm-publish:
    uses: christiangalsterer/github-actions/.github/workflows/node_npm_publish.yaml@main
    secrets: inherit
